name: 1 Deploy to Staging
on:
  push:
    branches: [main]

jobs:
  trigger:
    env:
      stack: provisioning
      #team: alpha
      #registry: ghcr.io
      registry: docker.pkg.github.com
      image_name: ${GITHUB_REPOSITORY##*/}
      target_org: firecyberice
      target_repo: actions-test

    name: Deploys the latest image to staging
    runs-on: ubuntu-latest
    steps:

#      - uses: bubkoo/use-app-token@v1
#        id: generate_token
#        with:
#          app_id: ${{ secrets.APP_ID }}
#          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get parameters
        id: gh_vars
        run: |
          set -e
          echo "::set-output name=sha::$(echo ${GITHUB_SHA:0:8})"
          echo "::set-output name=org::$(echo ${GITHUB_REPOSITORY%%/*})"
          echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY##*/})"
          echo "::set-output name=image::$(echo ${{ env.registry }}/$GITHUB_REPOSITORY/${{ env.image_name}})"
          set +e
         
      - name: Show variables
        run: |
          echo "list of variables"
          printf "%s: %20s\n" org "${{ steps.gh_vars.outputs.org }}"
          printf "%s: %20s\n" repo "${{ steps.gh_vars.outputs.repo }}"
          printf "%s: %20s\n" image "${{ steps.gh_vars.outputs.image }}"
          printf "%s: %20s\n" sha "${{ steps.gh_vars.outputs.sha }}"

      - name: Dispatch 'bump-image-tag-staging' message to K8s repo
        uses: mvasigh/dispatch-action@main
        with:
          event_type: bump-image-tag-staging
          # A personal access token with the 'repo' permission
          token: ${{ secrets.PAT }}
          # use github app to get rid of a personal access token
          #token: ${{ steps.generate_token.outputs.token }}
          owner: ${{ env.target_org }}
          repo: ${{ env.target_repo }}
          message: |
            {
              "image_name": "${{ steps.gh_vars.outputs.image }}",
              "image_tag": "${{ steps.gh_vars.outputs.sha }}",
              "service_name": "${{ steps.gh_vars.outputs.repo }}",
              "stack": "${{ env.stack }}"
            }
